name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    branches:
        - '**'

permissions: write-all

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: '3.12'
    - run: python -m pip install 'httpx[http2]' 'aiofiles'
    - name: Run
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GL_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        python -B -u main.py